version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: image_postgresql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    volumes:
      - ./dados_postgresql:/var/lib/postgresql/data:Z
    restart: always
