version: '3.9'
services:
  backend-esd:
    image: backend:latest
    build:
      dockerfile: Dockerfile
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
        PORT: ${DOCKER_PORT}
    container_name: backend-ilumeo
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    restart: always
    ports:
      - ${DOCKER_PORT}:${DOCKER_PORT}
    env_file:
      - .env
